language: java
cache:
  directories:
  - "$HOME/.cache"
script: mvn -B verify
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "acegiak"
  - git config --local user.email "acegiak@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "$githubOauth"
  file: "target/StorySpirit-1.1.jar"
  skip_cleanup: true