name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}

main: ${mainClass}

load: STARTUP

commands:
    name:
        description: Generate a name
        usage: /<command>
    spawn:
        description: Generate a new npc
        usage: /<command>

permissions: {}